import mongoose from 'mongoose';

const transactionSchema = new mongoose.Schema(
  {
    // Null for top-ups (money enters from M-Pesa, no internal sender).
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
      index: true,
    },
    // Required for topup/transfer; for withdrawal the receiver is the user
    // withdrawing (money leaves to their phone).
    receiver: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    amount: {
      type: Number,
      required: true,
      min: [1, 'Amount must be at least 1'],
    },
    type: {
      type: String,
      enum: ['topup', 'transfer', 'withdrawal'],
      required: true,
      index: true,
    },
    status: {
      type: String,
      enum: ['pending', 'success', 'failed', 'reversed'],
      default: 'pending',
      index: true,
    },
    // M-Pesa correlation identifiers.
    mpesaCheckoutRequestId: { type: String, index: true, sparse: true },
    mpesaReceiptNumber: { type: String, index: true, sparse: true },
    mpesaConversationId: { type: String, index: true, sparse: true },

    phone: { type: String },
    description: { type: String, maxlength: 200 },

    // Idempotency key. Uniqueness is enforced PER SENDER via the compound
    // partial index below — NOT globally — so the same key generated by two
    // different users can never collide (which would otherwise leak one
    // user's transaction to another or block a legitimate transfer).
    idempotencyKey: { type: String },

    // Raw Safaricom callback payloads kept for audit / reconciliation.
    metadata: { type: mongoose.Schema.Types.Mixed },
  },
  { timestamps: true }
);

// Common query path: a user's history sorted by recency.
transactionSchema.index({ receiver: 1, createdAt: -1 });
transactionSchema.index({ sender: 1, createdAt: -1 });

// Per-sender idempotency. The partial filter keeps rows WITHOUT a key (e.g.
// top-ups) out of the index entirely, so only (sender, idempotencyKey) pairs
// are constrained — and only when a key is actually present.
transactionSchema.index(
  { sender: 1, idempotencyKey: 1 },
  { unique: true, partialFilterExpression: { idempotencyKey: { $exists: true } } }
);

export const Transaction = mongoose.model('Transaction', transactionSchema);
export default Transaction;
