import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../lib/axios.js';

export const walletKeys = {
  balance: ['wallet', 'balance'],
  recipients: (q) => ['wallet', 'recipients', q],
};

/**
 * Wallet hook: balance query + peer-to-peer transfer mutation. The transfer
 * sends an Idempotency-Key header (generated by the caller) and, on success,
 * invalidates the balance and transaction queries so the UI auto-refreshes.
 */
export function useWallet() {
  const qc = useQueryClient();

  const balanceQuery = useQuery({
    queryKey: walletKeys.balance,
    queryFn: async () => {
      const { data } = await api.get('/api/wallet/balance');
      return data.data; // { balance, currency }
    },
  });

  const transferMutation = useMutation({
    mutationFn: async ({ recipientEmail, amount, description, idempotencyKey }) => {
      const { data } = await api.post(
        '/api/wallet/transfer',
        { recipientEmail, amount, description },
        { headers: { 'Idempotency-Key': idempotencyKey } }
      );
      return data.data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: walletKeys.balance });
      qc.invalidateQueries({ queryKey: ['transactions'] });
    },
  });

  return {
    balance: balanceQuery.data?.balance ?? 0,
    currency: balanceQuery.data?.currency ?? 'KES',
    balanceQuery,
    transfer: transferMutation.mutateAsync,
    transferMutation,
  };
}

/**
 * Debounced recipient search by name/email.
 * @param {string} query
 */
export function useRecipientSearch(query) {
  return useQuery({
    queryKey: walletKeys.recipients(query),
    enabled: query.trim().length >= 2,
    staleTime: 10_000,
    queryFn: async () => {
      const { data } = await api.get('/api/wallet/recipients', {
        params: { q: query.trim() },
      });
      return data.data.recipients; // [{ id, name, email }]
    },
  });
}

export default useWallet;
